kind: Pod
apiVersion: v1

metadata:
    name: pod-1

spec:
    containers:
        - name: pod1-container
          image: busybox:latest
          command: ["/bin/sh", "-c"]
          args:
              - echo "hello $(date)" >> /data/message.txt && sleep 3600
          volumeMounts:
              - name: pod1-vol
                mountPath: /data

    volumes:
        - name: pod1-vol
          emptyDir: {}