kind: Pod
apiVersion: v1

metadata:
    name: pv-pod

spec:
    containers:
        - name: pv-pod-container
          image: busybox:latest
          command: ["/bin/sh", "-c"]
          args:
              - echo "Hey there $(date)" >> /data/message.txt && sleep 3600
          volumeMounts:
              - name: pv-vol1
                mountPath: /data
    volumes:
        - name: pv-vol1
          persistentVolumeClaim:
              claimName: pvc-1 