kind: PersistentVolume
apiVersion: v1

metadata:
    name: pv-1

spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: /tmp/k8s-pv-data