kind: PersistentVolumeClaim
apiVersion: v1

metadata:
    name: pvc-auto

spec:
    storageClassName: standard
    accessModes: 
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi