---

- name: variable demo
  hosts: all
  become: true

  vars:
    app_name: terraweek-app
    app_port: 8080
    app_dir: "/opt/{{ app_name }}"
    packages:
      - git
      - curl
      - wget
  
  tasks:
    - name: Print app details
      debug:
        msg: "Deploying {{ app_name  }} on {{ app_port  }} to {{ app_dir  }}"

    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: install listed packages
      apt:
        name: "{{ packages  }}"
        state: present
