name: Test,Build and Deploy YAML file

# Trigger

on:
  push:
    branches: [main]

# Stages

jobs:
  #Job-1
  Test:
    name: Tests the code
    runs-on: ubuntu-latest

    steps: 
      - name: checkout
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: run tests
        run: npm test
  
  Build:
    name: build and push docker image
    runs-on: ubuntu-latest
    needs: Test

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build iamge
        run: docker build -t myapp:latest . 
      - name: push to dockerhub
        run: docker push myapp:latest
      
  Deploy:
    name: Deploy code
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: deploy code
        run: echo "Deploying application to staging server"




