name: Multi Job Workflow

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: build stage
              run: echo "Building The App"
    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: test stage
              run: echo "Testing The App"
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps: 
            - name: deploy stage
              run: echo "Deploying"

