kind: Pod
apiVersion: v1

metadata:
    name: secret-pod
    labels:
        app: my-secret-pod


spec:
    containers:
        - name: secret-pod-container
          image: busybox:latest
          command: ["sh", "-c", "sleep 3600"]
          env:
              - name: DB_USERNAME
                valueFrom:
                    secretKeyRef:
                        name: db-credentials
                        key: DB_USER
          volumeMounts:
              - name: secret-volume
                mountPath: "/etc/db-credentials"
                readOnly: true

    volumes:
      - name: secret-volume
        secret:
            secretName: db-credentials