name: secrets-file

on:
    workflow_dispatch:

jobs:
    secret-print:
        runs-on: ubuntu-latest
        steps:
            - name: checks if secret exists
              run: |
                if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
                    echo "Secret is Set: True"
                else
                    echo "Secret is not set: False"
                fi
            - name: print value of secret 
              run: echo "${{ secrets.MY_SECRET_MESSAGE }}"
            - name: passing secret as an ENV
              env:
                secret_msg: ${{ secrets.MY_SECRET_MESSAGE }}
              run: echo "secret loaded as env" && echo "Printing my secret message $secret_msg" && echo "printing 2nd secret message ${{ env.secret_msg }}" 
