[web]
web ansible_host=54.198.75.230

[app]
app ansible_host=52.91.156.119

[db]
db ansible_host=35.153.80.153

[application:children]
web
app
db

[all:vars]

ansible_user=ubuntu
ansible_ssh_private_key_file=ansible-prac